import { banners } from "./banners.js";
banners();
import { miniBanners } from "./mini-banners.js";
miniBanners();
import { dasteBandi2 } from "./daste-bandi2.js";
dasteBandi2();
import { berandHayeBartar } from "./berand-heye-barter.js";
berandHayeBartar();
import { banner2 } from "./banner2.js";
banner2();
import { dasteBandi1 } from "./daste-bandi1.js";
dasteBandi1();
import { menu } from "./menu.js";
menu();
